definitions:
  dto.ErrorResponse:
    properties:
      error:
        type: string
      message:
        type: string
    type: object
  models.Job:
    properties:
      createdAt:
        type: string
      filename:
        type: string
      id:
        type: string
      status:
        $ref: '#/definitions/models.JobStatus'
      updatedAt:
        type: string
    type: object
  models.JobStatus:
    enum:
    - QUEUED
    - PROCESSING
    - COMPLETED
    - FAILED
    type: string
    x-enum-varnames:
    - JobQueued
    - JobProcessing
    - JobCompleted
    - JobFailed
info:
  contact: {}
paths:
  /jobs:
    post:
      consumes:
      - multipart/form-data
      description: This endpoint allows you to create a new job by uploading a file,
        which will be saved in a temporary directory.
      parameters:
      - description: File to upload
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "201":
          description: Job created successfully
          schema:
            $ref: '#/definitions/models.Job'
        "400":
          description: Bad request, file missing in the form-data
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Internal server error, unable to create job
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Create a new job with file upload
      tags:
      - jobs
swagger: "2.0"
